version: '3.9'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A app.tasks.file_processing worker --loglevel=info --concurrency=8
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_flower:
    build: .
    command: celery -A app.tasks.file_processing flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - FLOWER_PORT=5555

volumes:
  redis_data:
